### PR TITLE
fix: 997 ack envelopes

### LINKED ISSUE #95: Generated acks always return with the `P` UsageIndicatorCode
https://github.com/Stedi-Demos/bootstrap/blob/80cbecb1adfa5de6c08c6515e46ae124cbe63a65/src/lib/acks.ts#L51

Currently all acks return with the usage indicator code set to `P`, even if the usage indicator is set to `T` or `I`. The X12 ack library should have a way of indicating what usage indicator code it should generate the 997 with.

### PR DESCRIPTION
**Pull request by RossWilliams**
- Send 1 997 per functional group. Previously sent 1 997 per interchange
- Switch to using x12-tools generate997. Allows customising envelope
- Re-use usage indicator code, release, and ISA-11 from incoming EDI

resolves #95

### CODE REVIEW

File: src/lib/acks.ts [hunk 1]
```diff
@@ -11,61 +11,112 @@ import {
...
-    sendingPartnerId,
-    receivingPartnerId,
-  } = input;
+  const { ackTransactionSet, interchange, functionalGroup } = input;
   const usageIndicatorCode = UsageIndicatorCodeSchema.parse(
     interchange.envelope?.usageIndicatorCode
   );
 
+  if (!interchange.envelope || !functionalGroup.envelope) {
+    return [];
```
Comment (rsioss) [inline src/lib/acks.ts:34]: nit: should this be an error? my expectation is that we'd only call `deliverAck` when these envelopes are available and there is something to be ack'd

File: src/lib/acks.ts [hunk 2]
```diff
@@ -11,61 +11,112 @@ import {
...
+  }
+
   // Generate control numbers for outbound 997
   const isaControlNumber = await generateControlNumber({
     segment: "ISA",
     usageIndicatorCode,
-    sendingPartnerId,
-    receivingPartnerId,
+    sendingPartnerId: input.receivingPartnerId,
+    receivingPartnerId: input.sendingPartnerId,
```
Comment (rsioss) [inline src/lib/acks.ts:42]: since the IDs from the actual envelope are used below in the `generate997` call, it might be better to remove them from the input signature entirely and just use the IDs from the envelope everywhere

**Review by rsioss — APPROVED** [review]
left two minor comments, but nothing blocking 🚢

File: src/lib/acks.ts (hunk 1 above)
Comment (rsioss) [reply src/lib/acks.ts:34]: @RossWilliams I definitely agree that the check should happen here. my feedback was more that I think this might be better treated as an error (throw here instead of a silent no-op, returning an empty array)
